package com.example.android_etpj;

public enum Type {
    FRAGMENT_HOME,FRAGMENT_ASSIGNMENT,FRAGMENT_CLASS,FRAGMENT_MODULE,FRAGMENT_ENROLLMENT,FRAGMENT_FEEDBACK,FRAGMENT_RESULT,FRAGMENT_QUESTION,FRAGMENT_CONTACT,FRAGMENT_JOIN,FRAGMENT_LOGOUT;
}
